#include "map.h"
#include <string.h>

unsigned char current_map[MAP_HEIGHT][MAP_WIDTH];

const unsigned char map_1[MAP_HEIGHT][MAP_WIDTH] = {
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE}
};

// Map 2: The Stone Dungeon (Stored in ROM)
const unsigned char map_2[MAP_HEIGHT][MAP_WIDTH] = {
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE}
};

void map_init(int map_index){
    const unsigned char (*src)[MAP_WIDTH] = (map_index == 2) ? map_2 : map_1;

    for (int row = 0; row < MAP_HEIGHT; row++){
        for(int col = 0; col < MAP_WIDTH; col++){
            current_map[row][col] = src[row][col];
        }
    }
}

void map_set_tile(int row, int col, SpriteID id){
    if (row >= 0 && row < MAP_HEIGHT && col >= 0 && col < MAP_WIDTH){
        current_map[row][col] = (unsigned char)id;
    }
}

SpriteID map_get_tile(int row, int col){
    if(row < 0 || row >= MAP_HEIGHT || col < 0 || col >= MAP_WIDTH){
        return SPRITE_TILE_STONE; //Return a solid tile if out of bounds so no crash
    }
    return (SpriteID)current_map[row][col];
}

