#include "map.h"
#include <string.h>

const MapConfig MAP_CONFIGS[] = {
    [0] = {0}, //unused

    /*Map 1: wetland/meadow */
    // - water patches, cattails, scattered trees
    [1] = {
        .tree_budget = 6,
        .rock_budget = 4,
        .small_budget = 4,
        .cattail_budget = 5,
        .fern_budget = 3,
        .tree_cluster_size = 2,
        .rock_cluster_size = 2,
        .prefer_big_trees = 1,
        .prefer_big_rocks = 0,
        .use_autumn_trees = 1,
        .use_stick_trees = 0,
        .use_ice_trees = 0,
        .use_grey_rocks = 2,
    },

    /* Map 2: Beach map*/
    // rock clusters, no water, no cattails
    [2] = {
        .tree_budget = 15,
        .rock_budget = 15,
        .bush_budget = 2,
        .small_budget = 10,
        .cattail_budget = 4,
        .fern_budget = 2,
        .tree_cluster_size = 4,
        .rock_cluster_size = 4,
        .prefer_big_trees = 2,
        .prefer_big_rocks = 1,
        .use_autumn_trees = 1,
        .use_stick_trees = 0,
        .use_ice_trees = 0,
        .use_grey_rocks = 1,
    },

    //ice map
    [3] = {
        .tree_budget = 8,
        .rock_budget = 3,
        .bush_budget = 1,
        .small_budget = 3,
        .cattail_budget = 0,
        .fern_budget = 1,
        .tree_cluster_size = 3,
        .rock_cluster_size = 5,
        .prefer_big_trees = 1,
        .prefer_big_rocks = 2,
        .use_autumn_trees = 0,
        .use_stick_trees = 1,
        .use_ice_trees = 2,
        .use_grey_rocks = 1, // Using blueish/white ice rocks
    },

    //rock map
    [4] = {
        .tree_budget = 4,
        .rock_budget = 25,
        .bush_budget = 0,
        .small_budget = 12,
        .cattail_budget = 0,
        .fern_budget = 0,
        .tree_cluster_size = 1,
        .rock_cluster_size = 6,
        .prefer_big_trees = 0,
        .prefer_big_rocks = 1,
        .use_autumn_trees = 0,
        .use_stick_trees = 2,
        .use_ice_trees = 0,
        .use_grey_rocks = 2, // Traditional grey stone
    },
};

unsigned char current_map[MAP_HEIGHT][MAP_WIDTH];

const unsigned char map_1[MAP_HEIGHT][MAP_WIDTH] = {
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE}
};

// Map 2: stoney beach
const unsigned char map_2[MAP_HEIGHT][MAP_WIDTH] = {
    {SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_GRASS, SPRITE_TILE_GRASS,  SPRITE_TILE_GRASS,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_GRASS,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND},
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER},
    {SPRITE_TILE_STONE, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER},
    {SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER},
    {SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER},
    {SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND},
    {SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_GRASS, SPRITE_TILE_GRASS, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT},
    {SPRITE_TILE_SAND,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS},
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_GRASS, SPRITE_TILE_GRASS}
};

//Ice map
const unsigned char map_3[MAP_HEIGHT][MAP_WIDTH] = {
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE}, 
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW}, 
    {SPRITE_TILE_STONE, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE}, 
    {SPRITE_TILE_STONE, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_WATER, SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_ICE,   SPRITE_TILE_WATER, SPRITE_TILE_SNOW,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE}, 
    {SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE}, 
    {SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_ICE,   SPRITE_TILE_WATER, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_STONE, SPRITE_TILE_STONE}, 
    {SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_STONE}, 
    {SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW}, 
    {SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW}, 
    {SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_STONE}, 
    {SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_WATER, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_STONE}, 
    {SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_WATER, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_WATER, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_SNOW,  SPRITE_TILE_STONE},
    {SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_WATER, SPRITE_TILE_WATER, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_STONE, SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_STONE, SPRITE_TILE_STONE}, 
    {SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_SNOW,  SPRITE_TILE_SNOW,  SPRITE_TILE_ICE,   SPRITE_TILE_ICE,   SPRITE_TILE_STONE}  
};

//rocky map
const unsigned char map_4[MAP_HEIGHT][MAP_WIDTH] = {
    {SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_SAND,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_SAND,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT},
    {SPRITE_TILE_SAND,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT},
    {SPRITE_TILE_SAND,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT},
    {SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT},
    {SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE},
    {SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT},
    {SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT},
    {SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_LAVA,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT},
    {SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_SAND},
    {SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND},
    {SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND},
    {SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_STONE, SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_DIRT,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND,  SPRITE_TILE_SAND}
};

void map_init(int map_index){
    const unsigned char (*src)[MAP_WIDTH] = (map_index == 4) ? map_4 : (map_index == 3) ? map_3 
                                            : (map_index == 2) ? map_2 : map_1;

    for (int row = 0; row < MAP_HEIGHT; row++){
        for(int col = 0; col < MAP_WIDTH; col++){
            current_map[row][col] = src[row][col];
        }
    }
}

void map_set_tile(int row, int col, SpriteID id){
    if (row >= 0 && row < MAP_HEIGHT && col >= 0 && col < MAP_WIDTH){
        current_map[row][col] = (unsigned char)id;
    }
}

SpriteID map_get_tile(int row, int col){
    if(row < 0 || row >= MAP_HEIGHT || col < 0 || col >= MAP_WIDTH){
        return SPRITE_TILE_STONE; //Return a solid tile if out of bounds so no crash
    }
    return (SpriteID)current_map[row][col];
}

