#ifndef ATTACK_1_SWORD_SWING_1_H
#define ATTACK_1_SWORD_SWING_1_H

/* Auto-generated by mp3_to_c_array.py
   Source : attack_1_sword_swing_1.mp3
   Rate   : 8000 Hz
   Length : 9024 samples (1.13s)
*/

#define ATTACK_1_SWORD_SWING_1_LENGTH 9024

const short attack_1_sword_swing_1[ATTACK_1_SWORD_SWING_1_LENGTH];

#endif /* ATTACK_1_SWORD_SWING_1_H */
