#!/usr/bin/env python3
"""
mp3_to_c_array.py - Convert MP3 files to C arrays for use with the audio system.

Usage:
    python mp3_to_c_array.py <input.mp3> [options]

Options:
    -o, --output    Output filename (default: input name with .h extension)
    -n, --name      Variable name (default: derived from filename)
    -r, --rate      Target sample rate (default: 8000 to match AUDIO_SAMPLE_RATE)
    -v, --volume    Normalize volume 0.0-1.0 (default: 1.0, no normalization)
"""

import argparse
import sys
import os
import re


def convert_mp3_to_c_array(
    input_path: str,
    output_path=None,
    var_name=None,
    sample_rate: int = 8000,
    normalize: float = 1.0,
):
    import numpy as np
    import librosa

    base = os.path.splitext(os.path.basename(input_path))[0]
    safe_base = re.sub(r'[^a-zA-Z0-9_]', '_', base).lower()

    if output_path is None:
        output_path = safe_base + ".h"
    if var_name is None:
        var_name = safe_base

    define_name = var_name.upper()

    print(f"Loading '{input_path}'...")
    # librosa handles mp3 via ffmpeg, returns float32 mono, resamples for you
    samples_f32, _ = librosa.load(input_path, sr=sample_rate, mono=True)

    if normalize < 1.0:
        peak = max(abs(samples_f32.max()), abs(samples_f32.min()), 1e-9)
        samples_f32 = samples_f32 / peak * normalize
        print(f"Normalized to {normalize:.2f} peak volume.")

    # Convert float32 [-1.0, 1.0] to int16
    samples = np.clip(samples_f32 * 32767, -32768, 32767).astype(np.int16)

    num_samples = len(samples)
    print(f"Total samples: {num_samples} ({num_samples / sample_rate:.2f} seconds)")

    print(f"Writing '{output_path}'...")
    guard = f"{define_name}_H"

    with open(output_path, "w") as f:
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write(f"/* Auto-generated by mp3_to_c_array.py\n")
        f.write(f"   Source : {os.path.basename(input_path)}\n")
        f.write(f"   Rate   : {sample_rate} Hz\n")
        f.write(f"   Length : {num_samples} samples ({num_samples / sample_rate:.2f}s)\n")
        f.write(f"*/\n\n")
        f.write(f"#define {define_name}_LENGTH {num_samples}\n\n")
        f.write(f"static const short {var_name}[{define_name}_LENGTH] = {{\n")

        cols = 12
        for i, s in enumerate(samples):
            if i % cols == 0:
                f.write("    ")
            f.write(f"{int(s)}")
            if i < num_samples - 1:
                f.write(", ")
            if (i + 1) % cols == 0:
                f.write("\n")

        if num_samples % cols != 0:
            f.write("\n")
        f.write("};\n\n")
        f.write(f"#endif /* {guard} */\n")

    print(f"Done. Include '{output_path}' and use:")
    print(f"    play_sfx({var_name}, {define_name}_LENGTH, 1.0f, 0);")
    print(f"    play_bgm({var_name}, {define_name}_LENGTH);")

def main():
    parser = argparse.ArgumentParser(
        description="Convert an MP3 file to a C short array for use with audio.h"
    )
    parser.add_argument("input", help="Input MP3 file")
    parser.add_argument("-o", "--output", help="Output .h filename")
    parser.add_argument("-n", "--name",   help="C variable name")
    parser.add_argument("-r", "--rate",   type=int, default=8000 ,
                        help="Sample rate in Hz (default: 8000)")
    parser.add_argument("-v", "--volume", type=float, default=1.0,
                        help="Normalize peak to this fraction of full scale (default: 1.0)")
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"Error: File '{args.input}' not found.")
        sys.exit(1)
    if not args.input.lower().endswith(".mp3"):
        print("Warning: Input file does not have a .mp3 extension, proceeding anyway...")
    if not (0.0 < args.volume <= 1.0):
        print("Error: --volume must be between 0.0 (exclusive) and 1.0 (inclusive).")
        sys.exit(1)

    convert_mp3_to_c_array(
        input_path=args.input,
        output_path=args.output,
        var_name=args.name,
        sample_rate=args.rate,
        normalize=args.volume,
    )


if __name__ == "__main__":
    main()